[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = ["."]

[project]
name = "sisimcp"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "numpy",
    "ruptures",
    "pytest",
    "requests",
    "python-dotenv",
    "mcp>=1.1.0",
    "fastmcp",
    "matplotlib",
    "flask",
    "sqlalchemy",
    "fastapi",
    "uvicorn",
    "jinja2",
    "pandas-stubs~=2.3.3",
    "griffe<1",
    "prefect>=3.0",
    "openai",
]

[tool.hatch.build.targets.wheel]
packages = ["mcp_conductor"]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.19.0",
]
